hipchat/hipchat-rb

lib/hipchat/client.rb

I could not send PM to others on my own hosted HipChat server without this patch.

bugfix: added missing server_url parameter

---

lib/hipchat/rails3_tasks.rb

When running the rake task I would get the error:
```
$ rake hipchat:send MESSAGE="hello world"
rake aborted!
HipChat::UnknownResponseCode: Unexpected 405 for room `'
```
This change fixed the issue for me.

Send call wasn't being passed the room name properly

---

lib/hipchat/capistrano2.rb

default message format is html for messages sent via `capistrano`; in order to make it not look bad, line separator will need to be set accordingly.
```
- text => "\n"
- html => "<br/>"
```

line separator depending on message_format

---

README.textile
lib/hipchat/capistrano/tasks/hipchat.rake
lib/hipchat/capistrano2.rb

hipchat_announce (while not a great name) is currently used to enable
user-notification of messages, not whether or not the task should send
any messages at all.
I've introduced :hipchat_enabled as an alternative to preserve the intent of #107 -- the ability to disable message sending entirely.
See https://www.hipchat.com/docs/apiv2/method/send_room_notification

Revert 86302c9e, fixes #131, reverts #107

---

spec/hipchat_spec.rb

This adds a regression test for af31d2c, which should have been the fix
for issue #129; references #130

Ensure the client options parameter remains usable

---

README.textile

Hey everyone,
When updating the hipchat gem (we use it in our deploy hooks), I started getting an error with the rake task.
```
HipChat::UnknownResponseCode: Unexpected 400 for room `<room>`
```
It looks like it was happening because the `color` option was being passed as nil (if you don't provide it in hipchat.yml). Per the API docs (https://www.hipchat.com/docs/apiv2/method/send_room_notification), color is optional; but in this case, the rake task always tries to pass it.
Simply adding `color` to the README might help people in the future.

Adds `color` to the hipchat.yml example for rake task.

---

lib/hipchat/errors.rb

In the current version of the hipchat gem when you want to deal with
hipchat exceptions you have to list all the possible exceptions that the
library can throw. This PR add a common base class to make rescuing a bit
easier.

Use a common parent class for all the errors

---

hipchat.gemspec

1.22.3 has a bug when using multiple stubs. Pinning the version of avoid hitting that.

Pin web mock to 1.22.1 to avoid 'query' string bug

---

lib/hipchat/api_version.rb
lib/hipchat/client.rb
lib/hipchat/room.rb
lib/hipchat/user.rb
spec/hipchat_api_v1_spec.rb
spec/hipchat_api_v2_spec.rb
spec/support/shared_contexts_for_hipchat.rb

Add Room#add_member method which allows to add member to room.
https://www.hipchat.com/docs/apiv2/method/add_member
Add Room#send_message method which allows to send message to room (as authenticated user).
https://www.hipchat.com/docs/apiv2/method/send_message
Add Client#create_user method which allows to create user in group
https://www.hipchat.com/docs/api/method/users/create
https://www.hipchat.com/docs/apiv2/method/create_user

Add support for 'add member', 'send message' and 'create user' in user/room API

---

lib/hipchat/client.rb
lib/hipchat/errors.rb
lib/hipchat/room.rb
lib/hipchat/user.rb
spec/hipchat_api_v1_spec.rb
spec/hipchat_api_v2_spec.rb

This change centralizing error handling into a single class and extends the supported exceptions to cover all v2 api error code responses.
New exceptions extend the `UnknownResponseCode` exception, to prevent any breaking changes.

StatusPage - Better error handling

---

lib/hipchat/api_version.rb
spec/hipchat_spec.rb

[Issue #139](https://github.com/hipchat/hipchat-rb/issues/139) fix. Raises the exception if incorrect api_version on Client initialzation.

Fix invalid api version, Issue #139

---

lib/hipchat/room.rb

According to the description of your project, v2 is supported. I made these changes to be v2-compatible. To really be robust, though, you'd probably want to use some value that changes according to version number.
Let me know what you think.

Account for longer usernames allowed in v2 of hipchat

---

lib/hipchat/capistrano/tasks/hipchat.rake

In some cases I want to able to overide the default application name  in the hipchat output.

Add support for specifying an alternative app name

---

lib/hipchat/user.rb

Apologies, on #168, I accidentally caused the syntaxes of the room send and direct send to diverge. This fixes that divergence.
before:
````ruby
hc.user(user).send(message, 'text', true)
````
after:
````ruby
hc.user(user).send(message, message_format: 'text', notify: true)
````

updated user send syntax to match room send, add configurable message-format

---

lib/hipchat/railtie.rb

Minimal steps to reproduce:
```
$ gem install rails
$ gem install hipchat
$ echo "require 'rails'" >> hipchat_test.rb
$ echo "require 'hipchat'" >> hipchat_test.rb
$ ruby -w hipchat_test.rb
... ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120: warning: loading in progress, circular require considered harmful ...
```

Fixes 'warning: loading in progress, circular require considered harmful'

---

hipchat.gemspec

Locking the versions of the addressable and json gems to the versions immediately before they stopped supporting Ruby 1.9.3.  
This seems like a maintenance problem; should hichat-rb drop Ruby 1.9 support instead?
The Travis build error:
> $ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
...
$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
public_suffix-2.0.4 requires ruby version >= 2.0, which is incompatible with the current version, ruby 1.9.3p551
For example: https://travis-ci.org/hipchat/hipchat-rb/jobs/177747406

Fix dependency issue that is breaking the Travis build

---

hipchat.gemspec

Update the gemspec to fix the following `bundle install` error in the 1.9.3 Travis build:
> term-ansicolor-1.4.0 requires ruby version >= 2.0, which is incompatible with the current version, ruby 1.9.3p551
Doing issue https://github.com/hipchat/hipchat-rb/issues/183 would be better!

Restrict term-ansicolor to a version that supports Ruby 1.9.3

---

lib/hipchat/errors.rb
lib/hipchat/room.rb

The `BadResponse` exception type is pretty much useless without explaining what went wrong—the provided message (`You may be missing a required argument or provided bad data`) is downright useless compared to the discarded response body, which actually helps provide an understanding of what is wrong with the request.
This pins a response to the exception, if there is a response to pin.

Add responses to exceptions!

---

lib/hipchat/api_version.rb
lib/hipchat/client.rb
spec/hipchat_api_v2_spec.rb
spec/support/shared_contexts_for_hipchat.rb

Added a method to the client class that returns scopes for an Auth token.
Calls the endpoint:
```    
https://api.hipchat.com/v2/oauth/token/#{token}
```
The response is a JSON object containing a client key. The client object contains a list of allowed scopes.
There are two possible response types, for a global API token, the room object will be nil:
```    
{
"client": {
"allowed_scopes": ["send_notification"],
"name": "Testing",
"room": null
},
"scopes": ["view_room", "send_notification"]
}
```
and for a room API token, the room object will be populated:
```
{
"client": {
"allowed_scopes": ["send_notification"],
"name": "testang",
"room": {
"id": 123456789,
"name": "example"
}
},
"scopes": ["send_notification"]
}
```
Optional room parameter can be passed into the method.
```
def …
```

Issue 199 - Added a method to return scopes for an auth token

---

lib/hipchat/errors.rb
spec/hipchat_error_handler_spec.rb

The conditional in `ServiceError#message` was failing with undefined method when calling `.present?` on `Net::HTTPResponse` instances:
```
def message
if @response.present?
"#{@msg}:\nResponse: #{@response.body}"
else
@msg
end
end
```
Changed the check for presence to a `.respond_to?` and added a spec for the ErrorHandler class.
```
def message
if @response.respond_to? :body
"#{@msg}:\nResponse: #{@response.body}"
else
@msg
end
end
```

Issue 197 - Undefined error message when calling ServiceError#message

---

lib/hipchat/api_version.rb
lib/hipchat/client.rb
lib/hipchat/room.rb
lib/hipchat/user.rb
spec/hipchat_api_v2_spec.rb
spec/support/shared_contexts_for_hipchat.rb

We added the reply endpoint to our fork of the gem and thought it might be useful to get it back on the main branch here.
Changes:
- Added `Room#reply` endpoint.
- Updated ruby version to `2.4.1`.
- Slightly less implied interpolation with the double quotes.

Added the reply endpoint

---

lib/hipchat/client.rb
spec/hipchat_api_v1_spec.rb
spec/hipchat_api_v2_spec.rb
spec/support/shared_contexts_for_hipchat.rb

Enable pagination, without which it is impossible to get more than 100 rooms or users.

Support pagination for fetching users and rooms
